Repository Haivision/srtgo, pull requests merged in 2021-07, with the labels that each got.

#25 return previously unused errors
  srtgo.go
Labels: enhancement

#24 fix non-blocking mode listening and blocking mode option parsing
  srtgo.go
Labels: bug

#29 Bugfix: set poll timeout
  netutils.go
  srtgo.go
Labels: bug

#31 reword readme a bit, add close calls to example
  README.md
Labels: documentation

#32 check and handle epoll-errors, use direction-specific epoll-handles
  errors.go
  srtgo.go
Labels: enhancement

#30 add binding for srt_connect_callback
  callback.h
  callback_c.go
  srtgo.go
Labels: enhancement

#34 Feature/pass polltimeout as duration
  README.md
  srtgo.go
Labels: enhancement

#35 Full errno handling
  errors.go
  srtgo.go
  srtsocketoptions.go
Labels: enhancement

#37 Optimize error handling & improve non-blocking performance
  read.go
  srtgo.go
  write.go
Labels: enhancement
